--[[
	@author: psychol.
]]

VEHICLES_LIST={
	["Banshee"]="sport5",
	["Sultan"]="sport5",
	["Police SF"]="sport5",
	["Buffalo"]="sport5",
	["Bullet"]="sport2",
	["Cheetah"]="sport2",
	["Comet"]="sport1",
	["Elegy"]="sport4",
	["Infernus"]="sport2",
	["Jester"]="sport4",
	["Super GT"]="sport3",
	["Turismo"]="sport2",
	["ZR-350"]="sport4",
	["Alpha"]="sport4",
	["Euros"]="sport4",
	["Blista Compact"]="casual2",
	["Premier"]="casual2",
	["Sentinel"]="casual2",
	["Taxi"]="casual2",
	["FBI Rancher"]="casual5",
	["Patriot"]="casual5",
	["Police LS"]="casual2",
	["Police LV"]="casual2",
	["Huntley"]="casual5",
	["Flash"]="sport4",
	["Hotring Racer"]="sport4",
	["Hotring Racer 2"]="sport4",
	["Hotring Racer 3"]="sport4",
	["Stratum"]="casual2",
	["Uranus"]="casual2",
	["Windsor"]="casual2",
	["BF Injection"]="casual5",
	["Sandking"]="casual5",
	["Merit"]="casual2",
	["Fortune"]="casual2",
	["Elegant"]="casual2",
	["Washington"]="casual2",
	["Baggage"]="casual5",
	["Bus"]="bus1",
	["Coach"]="bus1",
	["Towtruck"]="casual5",
	["Trashmaster"]="truck3",
	["Ambulance"]="casual5",
	["Barracks"]="truck3",
	["Enforcer"]="truck3",
	["FBI Truck"]="truck2",
	["Fire Truck"]="truck3",
	["Fire Ladder"]="truck2",
	["Securicar"]="truck2",
	["Benson"]="truck1",
	["Black Boxville"]="truck1",
	["Boxville"]="truck1",
	["Cement Truck"]="truck3",
	["DFT-30"]="truck2",
	["Dozer"]="truck2",
	["Dumper"]="truck2",
	["Dune"]="truck2",
	["Flatbed"]="truck3",
	["Hotdog"]="truck1",
	["Linerunner"]="truck3",
	["Mr. Whoopee"]="casual5",
	["Mule"]="truck1",
	["Packer"]="truck2",
	["Roadtrain"]="truck3",
	["Tanker"]="truck3",
	["Yankee"]="truck1",
	["Buccaneer"]="muscle2",
	["Savanna"]="muscle1",
	["Hustler"]="muscle1",
	["Hermes"]="muscle2",
	["Blade"]="muscle2",
	["Remington"]="muscle3",
	["Broadway"]="muscle2",
	["Slamvan"]="muscle3",
	["Tornado"]="muscle1",
	["Voodoo"]="muscle2",
	["Sabre"]="muscle2",
	["Phoenix"]="muscle3",
	["Clover"]="muscle1",
	["Hotknife"]="muscle3",
	["BF-400"]="motorbike3",
	["Faggio"]="motorbike1",
	["FCR-900"]="motorbike3",
	["Freeway"]="motorbike5",
	["NRG-500"]="motorbike2",
	["Pizza Boy"]="motorbike1",
	["Sanchez"]="motorbike3",
	["Wayfarer"]="motorbike4",
	["Quadbike"]="motorbike4",
	["HPV1000"]="motorbike4",
	["Bravura"]="casual4",
	["Cadrona"]="casual4",
	["Club"]="casual2",
	["Esperanto"]="casual4",
	["Feltzer"]="casual4",
	["Majestic"]="casual4",
	["Manana"]="casual4",
	["Picador"]="casual4",
	["Previon"]="casual4",
	["Stallion"]="casual4",
	["Tampa"]="casual2",
	["Virgo"]="casual4",
	["Admiral"]="casual2",
	["Damaged Glendale"]="casual4",
	["Emperor"]="casual4",
	["Glendale"]="casual4",
	["Greenwood"]="casual4",
	["Intruder"]="casual4",
	["Nebula"]="casual4",
	["Oceanic"]="casual4",
	["Primo"]="casual4",
	["Stafford"]="casual4",
	["Stretch"]="casual2",
	["Sunrise"]="casual2",
	["Tahoma"]="casual2",
	["Vincent"]="casual4",
	["Willard"]="casual4",
	["Cabbie"]="casual4",
	["Utility Van"]="casual5",
	["Police Ranger"]="casual5",
	["Berkley's RC Van"]="casual5",
	["Bobcat"]="casual4",
	["Burrito"]="causal2",
	["Moonbeam"]="casual4",
	["Pony"]="casual5",
	["Rumpo"]="casual5",
	["Sadler"]="casual4",
	["Tug"]="casual4",
	["Walton"]="casual3",
	["Yosemite"]="casual5",
	["Landstalker"]="casual5",
	["Perennial"]="casual3",
	["Rancher"]="casual5",
	["Regina"]="casual4",
	["Romero"]="casual4",
	["Solair"]="casual4",
	["Bandito"]="casual2",
	["Caddy"]="casual4",
	["Camper"]="casual5",
	["Journey"]="casual5",
	["Mesa"]="casual5",
	["Monster"]="casual5",
	["Monster 2"]="casual5",
	["Monster 3"]="casual5",
	["Tractor"]="truck3",
	["Newsvan"]="casual5",
}

local types={
	['Automobile']=true,
	['Quad']=true,
	['Bike']=true,
}

function getVehicleSoundPack(veh)
	local vehName=getVehicleName(veh)
	
	if(vehName == "S.W.A.T")then return false end
	if(not types[getVehicleType(veh)])then return false end

	local info={
		soundPack=(VEHICLES_LIST[vehName] or "casual2"),

		idleRPM=1000,
		maxRPM=10000,
		shiftDownRPM=3500,
		shiftUpRPM=6500,
	}

	return info
end